services:
  mcp-system-info:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mcp-network
    environment:
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Мониторинг здоровья
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mcp-network:
    driver: bridge